# Generated by Django 3.0.8 on 2020-07-31 01:00

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='articles/')),
            ],
        ),
        migrations.CreateModel(
            name='Article_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='news_documents/%Y/%m/', validators=[main.validators.validate_file_extension])),
                ('index', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article_doc_id', to='main.Article')),
            ],
        ),
    ]
