# Generated by Django 3.0.8 on 2020-08-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=5000)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('coordinator', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('Planificación', 'Planificación'), ('Diseño', 'Diseño'), ('Desarrollo', 'Desarrollo'), ('Construcción', 'Construcción'), ('Evaluatión', 'Evaluación'), ('Optimización', 'Optimización')], default='Planificación', max_length=50)),
            ],
        ),
    ]
