# Generated by Django 3.0.8 on 2020-08-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
