# Generated by Django 3.0.8 on 2020-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200803_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=5000)),
                ('mail', models.EmailField(max_length=300)),
                ('member_link', models.CharField(max_length=150)),
                ('random_fact', models.CharField(max_length=500)),
                ('twitter_link', models.CharField(max_length=150)),
                ('research_link', models.CharField(max_length=150)),
                ('banco_ideas_link', models.CharField(max_length=150)),
                ('img', models.ImageField(null=True, upload_to='members/')),
                ('legion', models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('Optimización', 'Optimización')], default='2020', max_length=50)),
            ],
        ),
    ]
