# Generated by Django 3.0.8 on 2020-08-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='body',
            new_name='bodyEN',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='state',
            new_name='stateES',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='titleEN',
        ),
        migrations.AddField(
            model_name='project',
            name='bodyES',
            field=models.TextField(default='update this', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stateEN',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Design', 'Design'), ('Development', 'Development'), ('Building', 'Building'), ('Evaluation', 'Evaluation'), ('Optimization', 'Optimization')], default='Planning', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='titleES',
            field=models.CharField(default='update this', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='legion',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2020', max_length=50),
        ),
    ]
